# -*- coding: utf-8 -*-
"""Weather Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBeb00Nl2N7Fa2hYwvCGQad5U3UgTmle
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Project+1+-+Weather+Dataset.csv')
df.head(10)

df.shape

print("Number of Rows",df.shape[0])
print("Number of Columns",df.shape[1])

df.index

df.columns

df.dtypes

df['Weather'].unique()

df.nunique()

df.count()

df['Weather'].value_counts()

df.info()

df.describe()

df['Wind Speed_km/h'].unique()

df.Weather.value_counts()

df[df.Weather == 'Clear']

df.groupby('Weather').get_group('Clear')

df[df['Wind Speed_km/h'] == 4]

df.isnull().sum()

df.notnull().sum()

df.rename(columns={'Weather':'Weather Condition'},inplace=True)

df.head(2)

df.Visibility_km.mean()

df.Press_kPa.std()

df['Rel Hum_%'].var()

df.columns

df['Weather Condition'].value_counts()

df[df['Weather Condition'] == 'Snow']

df[df['Weather Condition'].str.contains('Snow')]

df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km'] == 25)]

df.groupby('Weather Condition').mean(numeric_only=True)

df.groupby('Weather Condition').min(numeric_only=True)

df.groupby('Weather Condition').max(numeric_only=True)

df[df['Weather Condition'] == 'Fog']

df[(df['Weather Condition'] == 'Clear') | (df['Visibility_km'] > 40)]

df.columns

df[(df['Weather Condition'] == 'Clear') & (df['Rel Hum_%'] > 50) | (df['Visibility_km'] > 40) ]

